services:
  vault:
    image: hashicorp/vault:latest
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200" # Expose the Vault API
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    networks:
      - backtier

  myproject:
    build:
      context: ./Backend/myproject
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - vault
    networks:
      - backtier

  gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - vault
      - myproject
    volumes:
      - frontend_dist:/usr/share/nginx/html
    networks:
      - backtier

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    volumes:
      - frontend_dist:/app/dist # Mount volume to persist the dist/ folder
    networks:
      - backtier
      - frontier

volumes:
  frontend_dist: # Define the shared volume

networks:
  backtier:
    driver: bridge
  frontier:
    driver: bridge
