services:
  vault:
    image: hashicorp/vault:latest
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200" # Expose the Vault API
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    networks:
      - backend_network

  myproject:
    build:
      context: ./Backend/myproject
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - vault
    networks:
      - backend_network

  gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - vault
      - myproject
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
