services:

  # swagger:
  #   container_name: swagger
  #   build:
  #     context: ./Swagger
  #     dockerfile: Dockerfile
  #   environment:
  #     URLS_PRIMARY_NAME: "UserService" # Default API to display in Swagger UI
  #     URLS: '[{ "url": "/doc/ApiGateway.yaml", "name": "ApiGateway" }, 
  #        { "url": "/doc/UserService.yaml", "name": "UserService" },
  #        { "url": "/doc/Security.yaml", "name": "Security" },
  #        { "url": "/doc/Database.yaml", "name": "Database" },
  #        { "url": "/doc/FrontEnd.yaml", "name": "FrontEnd" }]'
  #   volumes:
  #     - ./docs/openapi:/usr/share/nginx/html/doc # Mount local OpenAPI specs
  #   ports:
  #     - "8080:8080"  # Swagger UI available at localhost:8080
  #   restart: always
  #   networks:
  #     backtier:

  vault:
    container_name: vault
    build:
      context: ./Security/Vault
      dockerfile: Dockerfile
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    networks:
      - backtier
    environment:
      - VAULT_ADDR=http://vault:8200
    volumes:
      - ./Security/Vault/config:/vault/config
      - secrets:/secrets
      - ./Security/VaultSecrets/secrets/.env:/secrets/.env
    healthcheck:
      test: ["CMD", "vault", "status", "-address=http://localhost:8200"]
      interval: 10s
      timeout: 5s
      retries: 5

  vault_secrets:
    container_name: vault_secrets
    build:
      context: ./Security/VaultSecrets
      dockerfile: Dockerfile
    env_file:
      - ./Security/VaultSecrets/secrets/.env
    networks:
      - backtier
    depends_on:
      vault:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./Security/VaultSecrets/secrets:/secrets

  user:
    container_name: user
    build:
      context: ./Backend/userService
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/userService:/app
      - ./vault-agent-config:/vault/agent/config # Mount Vault Agent config
      - ./secrets/user_service:/vault/secrets # mounted role_id/secret_id
    environment:
      VAULT_ADDR: "http://vault:8200"
    depends_on:
      - vault
      - user_db
    networks:
      - backtier

  user_db:
    container_name: user_db
    build:
      context: ./Database/user_db
      dockerfile: Dockerfile
    image: postgres:latest
    depends_on:
      - vault
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d postgres -U postgres || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports: 
      - "5432:5432" # or Expose syntax like expose: -5432
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - backtier

  gateway:
    container_name: gateway
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
      args:
        - CURRENT_HOST=localhost
    environment:
      - CURRENT_HOST=localhost
    ports:
      - 80:80
      - 443:443
    depends_on:
      - vault
      - user
      - frontend
    volumes:
      - ./ApiGateway/config/nginx.conf.template:/nginx.conf.template
      - frontend_dist:/usr/share/nginx/html
      - ./.cert/:/etc/nginx/ssl/
    networks:
      - backtier

  frontend:
    container_name: frontend
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    volumes:
      - ./FrontEnd:/app
      - frontend_dist:/app/dist # Mount volume to persist the dist/ folder
    networks:
      - backtier
      - frontier

volumes:
  frontend_dist:
  user_db_data:
  secrets: # this is the shared volume between vault and vault_secrets

networks:
  backtier:
    driver: bridge
    name: backtier
  frontier:
    driver: bridge
    name: frontier
