services:
  keystore_n_certs:
    image: elasticsearch:${ELK_VERSION}
    command: bash /setup/setup-certs.sh
    user: "0"
    volumes:
        - ./elk/secrets:/secrets
        - ./elk/setup/:/setup/
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELK_VERSION: ${ELK_VERSION}
      