# Generated by Django 5.1.2 on 2024-11-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_newtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewTable',
        ),
    ]
