services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # Limit Java heap size
    ports:
      - "9200:9200"
    networks:
      - backtier
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.2
    container_name: logstash
    volumes:
      - ./elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "5044:5044"
    networks:
      - backtier

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.2
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - backtier
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.17.2
    container_name: filebeat
    user: root
    volumes:
      - ./elk/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /../../goinfre/${USER}/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - logstash
    networks:
      - backtier

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.17.2
    container_name: metricbeat
    user: root
    volumes:
      - ./elk/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock  # Tell Metricbeat to use Docker socket
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - backtier

networks:
  backtier:
    driver: bridge
