{
 "title": "cAdvisor Dashboard",
 "description": "Dashboard for Docker containers",
 "tags": [
  "Docker",
  "cAdvisor",
  "Prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total,job)"
    }
   },
   {
    "name": "container",
    "label": "Container(s)",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{job=~\"$job\", instance=~\"$instance\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"$instance\",job=~\"$job\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "CPU usage on instance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}[$interval])) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network traffic on instance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$instance\",id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{instance=~\"$instance\",id=\"/\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage per container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$container\",name=~\".+\",instance=~\"$instance\",image!=\"\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory usage per container",
   "type": "timeseries",
   "description": "Preferred way to view memory usage, Portainer also uses this method compared to showing RSS memory usage.\n\n**NOTE**: This graph joins all containers with the same name together sometimes causing visible memory usage spikes (on the graph) when recreating containers. Toggle the `Split Containers` query in the panel editing UI to change this behavior.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=~\"$instance\",job=~\"$job\",name=~\"$container\",name=~\".+\",image!=\"\"}) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RSS memory per container",
   "type": "timeseries",
   "description": "**NOTE**: This graph joins all containers with the same name together sometimes causing visible memory usage spikes (on the graph) when recreating containers. Toggle the `Split Containers` query in the panel editing UI to change this behavior.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$instance\",job=~\"$job\",name=~\"$container\",name=~\".+\",image!=\"\"}) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory cached per container",
   "type": "timeseries",
   "description": "**NOTE**: This graph joins all containers with the same name together sometimes causing visible memory usage spikes (on the graph) when recreating containers. Toggle the `Split Containers` query in the panel editing UI to change this behavior.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{instance=~\"$instance\",job=~\"$job\",name=~\"$container\",name=~\".+\",image!=\"\"}) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Sent network traffic per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$instance\",job=~\"$job\",name=~\"$container\",name=~\".+\",image!=\"\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received network traffic per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$instance\",job=~\"$job\",name=~\"$container\",name=~\".+\",image!=\"\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{instance=~\"$instance\",job=~\"$job\",name=~\"$container\",name=~\".+\",image!=\"\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{instance=~\"$instance\",job=~\"$job\",name=~\"$container\",name=~\".+\",image!=\"\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}