# Generated by Django 5.1.6 on 2025-02-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userService', '0004_remove_message_chat_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='avatars/'),
        ),
    ]
