# Generated by Django 5.1.3 on 2024-11-19 11:02

import userService.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userService', '0006_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to=userService.models.upload_to),
        ),
    ]
