# Generated by Django 5.1.3 on 2024-11-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userService', '0007_remove_profile_avatar_profile_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchhistory',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='match_history',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wins',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='MatchHistory',
        ),
    ]
