# Generated by Django 5.1.2 on 2025-02-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertotp',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
