filebeat.inputs:
  - type: container
    paths:
      - "/var/lib/docker/containers/*/*.log"
    # processors:
    #   - add_docker_metadata: ~
    #   - add_host_metadata: ~
    #   - decode_json_fields:
    #       fields: ["log"]
    #       target: ""
    #       overwrite_keys: true
    # fields:
    #   log_type: docker
    # multiline.pattern: '^\s'
    # multiline.negate: false
    # multiline.match: after
    
    # json:
    #   keys_under_root: true
    #   add_error_key: true
    #   message_key: "log" 

output.logstash:
  hosts: ["logstash:5044"]

# output.elasticsearch:
#   hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"
