metricbeat.modules:
  - module: system
    metricsets: ["process", "cpu", "memory", "network"]
    period: 10s
    processors:
      - add_host_metadata: ~
      - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
