# Generated by Django 5.1.6 on 2025-03-01 18:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='game_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
