# Generated by Django 5.1.2 on 2025-02-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='ball_direction',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='ball_position',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player1_paddle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player2_paddle',
            field=models.IntegerField(default=0),
        ),
    ]
