# Generated by Django 5.1.6 on 2025-03-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='tournament_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
